server:
  port: 8081

spring:
  application:
    name: foodybuddy-orders
  datasource:
    url: jdbc:h2:mem:ordersdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodybuddy.orders: DEBUG

# External service configuration
gateway:
  url: http://localhost:8080
