server:
  port: 8081

spring:
  application:
    name: foodybuddy-orders
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:foodybuddy}?currentSchema=${DB_SCHEMA_ORDERS:orders}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:foodybuddy_user}
    password: ${DB_PASSWORD:foodybuddy_password}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders
        format_sql: false
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodybuddy.orders: ${LOG_LEVEL_ORDERS:DEBUG}

# External service configuration
gateway:
  url: ${GATEWAY_URL:http://foodybuddy-gateway:8080}
