server:
  port: 8081

spring:
  application:
    name: foodybuddy-orders
  datasource:
    url: jdbc:postgresql://postgres:5432/foodybuddy?currentSchema=orders
    driverClassName: org.postgresql.Driver
    username: foodybuddy_user
    password: foodybuddy_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders
        format_sql: false
  main:
    lazy-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodybuddy.orders: DEBUG

# External service configuration
gateway:
  url: http://foodybuddy-gateway:8080
